[package]
name = "ivtools"
version = "0.1.0"
authors = ["Seth Stadick <sstadick@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-lapper = {path = "../rust-lapper"}
scailist = {path = "../ScAIList"}
